version: "3.8"
   
services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=vinyls
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ./sql/data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  web:
    build: .
    command: npm run start:prod
    volumes:
      - /usr/src/app
    environment:
      DB_HOST: "db"
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - default


volumes:
  pgdata: